-- =====================================================
-- Project: PFinance Customer Onboarding Analytics
-- File: 07_revenue_impact_analysis.sql
-- Description: Estimate the revenue opportunity from improving
-- onboarding completion.
-- =====================================================

-- Business Question:
-- What is the total transaction value generated by users
-- who completed onboarding?

SELECT
    COUNT(*) AS completed_users,
    ROUND(AVG(transaction_amount),2) AS average_transaction_amount,
    ROUND(SUM(transaction_amount),2) AS total_revenue
FROM users
WHERE completed_onboarding = 'Yes';